 
require(remotes)
remotes::install_version("glue",upgrade="never", version = "1.4.2")
remotes::install_version("processx",upgrade="never", version = "3.4.4")
remotes::install_version("htmltools",upgrade="never", version = "0.5.1.1")
remotes::install_version("htmlwidgets",upgrade="never", version = "1.5.3")
remotes::install_version("pkgload",upgrade="never", version = "1.1.0")
remotes::install_version("attempt",upgrade="never", version = "0.3.1")
remotes::install_version("testthat",upgrade="never", version = "3.0.0")
remotes::install_version("shiny",upgrade="never", version = "1.6.0")
remotes::install_version("config",upgrade="never", version = "0.3")
remotes::install_github("Thinkr-open/golem@aaae5c8788802a7b4aef4df23691902a286dd964")
remotes::install_version("shinydashboardPlus",upgrade="never", version = "2.0.0")
remotes::install_version("shinydashboard",upgrade="never", version = "0.7.1")
remotes::install_version("tidyverse",upgrade="never", version = "1.3.0")
remotes::install_version("shinyWidgets",upgrade="never", version = "0.5.4")
remotes::install_version("leaflet",upgrade="never", version = "2.0.3")
remotes::install_version("sf",upgrade="never", version = "0.9-6")
remotes::install_version("DBI",upgrade="never", version = "1.1.0")
remotes::install_version("rpostgis",upgrade="never", version = "1.4.3")
remotes::install_version("ggplot2",upgrade="never", version = "3.3.2")
remotes::install_version("rgdal",upgrade="never", version = "1.5-18")
remotes::install_version("shinyjs",upgrade="never", version = "2.0.0")
remotes::install_version("sp",upgrade="never", version = "1.4-4")
remotes::install_version("DT",upgrade="never", version = "0.16")
remotes::install_version("rmarkdown",upgrade="never", version = "2.5")
remotes::install_version("knitr",upgrade="never", version = "1.30")
remotes::install_version("tidyr",upgrade="never", version = "1.1.2")
remotes::install_version("pool",upgrade="never", version = "0.1.6")
remotes::install_version("waiter",upgrade="never", version = "0.1.3")
remotes::install_version("promises",upgrade="never", version = "1.2.0.1")
remotes::install_version("future",upgrade="never", version = "1.21.0")
remotes::install_version("shinyalert",upgrade="never", version = "2.0.0")
remotes::install_version("bs4Dash",upgrade="never", version = "0.5.0")
remotes::install_version("plotly",upgrade="never", version = "4.9.3")
remotes::install_version("cartography",upgrade="never", version = "3.0.0")
remotes::install_version("osmdata",upgrade="never", version = "0.1.5")
remotes::install_version("shinycssloaders",upgrade="never", version = "1.0.0")
remotes::install_version("webshot",upgrade="never", version = "0.5.2")
remotes::install_version("tinytex",upgrade="never", version = "0.32")
tinytex::install_tinytex()
remotes::install_version("shinydisconnect",upgrade="never", version = "0.1.0")
remotes::install_version("leafgl",upgrade="never", version = "0.1.1")
remotes::install_version("emayili",upgrade="never", version = "0.4.15")
remotes::install_version("shinybusy",upgrade="never", version = "0.2.2")
