proxy:
  title: Safe Streets Priority Finder
  landing-page: https://highriskstreetsfinder.com/app/safe-streets-priority-finder
  hide-navbar: true
  heartbeat-rate: 10000
  heartbeat-timeout: 1800000
  container-wait-time: 120000
  port: 8080
  #### OpenID Connect Authentication ####
  authentication: none # use openid auth framework

  docker:
      internal-networking: true

  # Below is a list of Shiny app and their config (including who can access to which)
  specs:
    - id: safe-streets-priority-finder
      display-name: Safe Streets Priority Finder
      container-cmd: ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');safer_streets_priority_finder::run_app()"]
      container-image: tooledesign/vulusr_beta
      container-network: sp-net

server:
  useForwardHeaders: true # this is very important to make the AWS Cognito auth working

logging:
  file:
    shinyproxy.log

