
Sys.setenv(SSPF_EMAIL_PASSWORD="")

Sys.setenv(SSPF_EMAIL_ADDRESS="")

Sys.setenv(SSPF_AMAZON_HOST_ADDRESS="")

Sys.setenv(SSPF_AMAZON_PASSWORD="")

Sys.setenv(SSPF_AMAZON_USERNAME="")

Sys.setenv(SSPF_AMAZON_DATABASE="")